apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-alxv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0076-tenant/ci1t-830-0076-app/devfile-sample-alxv@sha256:841663912d56e535405adaf96d09c6b72bfa11407c557a7380d771c7cc5190d9
        name: my-nodejs
        resources: {}
status: {}
